Repository DO-SOPT-CDS-APP-7/Kurly-iOS, pull requests merged in 2023-12, with the labels that each got.

#106 [Feature] #95 - 다른 사람이 함께 본 상품 조회 API를 연결하였습니다.
  Kurly/Kurly.xcodeproj/project.pbxproj
  Kurly/Kurly/Network/DTO/RelatedRequest.swift
  Kurly/Kurly/Network/DTO/RelatedResponse.swift
  Kurly/Kurly/Network/Service/ProductService.swift
  Kurly/Kurly/Presentation/AddCart/ViewControllers/AddCartViewController.swift
  Kurly/Kurly/Presentation/AddCart/Views/AddCartView.swift
  Kurly/Kurly/Presentation/AfterAddCart/ViewControllers/AfterAddCartViewController.swift
  Kurly/Kurly/Presentation/AfterAddCart/Views/AfterAddCartView.swift
  Kurly/Kurly/Presentation/Common/UIComponents/CustomCollectionView/CustomCollectionView.swift
Labels: Feature, 민주

#104 [Fix] 다른 고객이 본 상품, 함께 구매하면 좋은 상품을 수정하겠습니다. #103
  Kurly/Kurly/Network/Service/RecommendService.swift
  Kurly/Kurly/Presentation/AfterAddCart/Model/RelatedModel.swift
  Kurly/Kurly/Presentation/Common/UIComponents/CustomCollectionView/CustomCollectionView.swift
  Kurly/Kurly/Presentation/RelatedFoodModal/Views/RelatedFoodModalView.swift
Labels: Fix, 민수

#107 [Feature] #91 - 장바구니 조회 API 및 데이터 유무를 통한 화면 변경 구현했습니다
  Kurly/Kurly.xcodeproj/project.pbxproj
  Kurly/Kurly/Network/DTO/CartResponse.swift
  Kurly/Kurly/Network/Service/CartCheckService.swift
  Kurly/Kurly/Presentation/Cart/Cells/CartItemCollectionViewCell.swift
  Kurly/Kurly/Presentation/Cart/Cells/OrderPriceCollectionViewCell.swift
  Kurly/Kurly/Presentation/Cart/Model/CartModel.swift
  Kurly/Kurly/Presentation/Cart/Model/OrderModel.swift
  Kurly/Kurly/Presentation/Cart/ViewControllers/CartViewController.swift
  Kurly/Kurly/Presentation/Cart/Views/CartHeaderView.swift
  Kurly/Kurly/Presentation/Cart/Views/CartView.swift
  Kurly/Kurly/Presentation/Common/UIComponents/BottomCTAButton.swift
Labels: Feature, Fix, 준혁, UI

#105 [Fix] #100 - 커스텀 컬렉션 뷰로 수정하고 API 연결합니다.
  Kurly/Kurly.xcodeproj/project.pbxproj
  Kurly/Kurly/Network/DTO/RelatedResponseV2.swift
  Kurly/Kurly/Network/Service/ProductService.swift
  Kurly/Kurly/Network/Service/RelatedProductService.swift
  Kurly/Kurly/Presentation/Detail/Cells/ThridSectionHorizontalCollectionViewCell.swift
  Kurly/Kurly/Presentation/Detail/ViewControllers/DetailViewController.swift
  Kurly/Kurly/Presentation/Detail/Views/DetailView.swift
Labels: Fix, 보연
