Repository DO-SOPT-CDS-APP-7/Kurly-iOS, pull requests merged in 2023-11, with the labels that each got.

#4 [Setting] #3 - BaseView, BaseViewController를 만들었습니다.
  Kurly/Kurly.xcodeproj/project.pbxproj
  Kurly/Kurly/Global/Extension/NSObject+.swift
  Kurly/Kurly/Presentation/Common/Base/BaseView.swift
  Kurly/Kurly/Presentation/Common/Base/BaseViewController.swift
Labels: 민주, Setting

#6 [Feature] #5 - Custom Navigation Bar, 상세조회 뷰 상단 TabBar를 구현했습니다.
  Kurly/Kurly.xcodeproj/project.pbxproj
  Kurly/Kurly/Application/SceneDelegate.swift
  Kurly/Kurly/Global/Extension/UICollectionView+.swift
  Kurly/Kurly/Global/Literals/ColorLiterals.swift
  Kurly/Kurly/Global/Literals/FontLiterals.swift
  Kurly/Kurly/Global/Literals/ImageLiterals.swift
  Kurly/Kurly/Global/Literals/Literal/ColorLiterals.swift
  Kurly/Kurly/Global/Literals/SizeLiterals.swift
  Kurly/Kurly/Global/Literals/String/String.swift
  Kurly/Kurly/Global/Resources/Info.plist
  Kurly/Kurly/Global/SupportingFiles/Base/Base1.swift
  Kurly/Kurly/Presentation/Common/TabBar/TabBarCollectionView.swift
  Kurly/Kurly/Presentation/Common/TabBar/TabBarCollectionViewCell.swift
  Kurly/Kurly/Presentation/Common/TabBar/TabBarRect.swift
  Kurly/Kurly/Presentation/Common/TabBar/TabBarView.swift
  Kurly/Kurly/Presentation/Common/UIComponents/CustomNavigationBar.swift
  Kurly/Kurly/Presentation/Detail/ViewController/DetailViewController.swift
Labels: Feature, 민주, Setting

#8 [Feature] #7 - 하단 CTA 버튼을 구현했습니다.
  Kurly/Kurly.xcodeproj/project.pbxproj
  Kurly/Kurly/Presentation/Common/TabBar/TabBarCollectionView.swift
  Kurly/Kurly/Presentation/Common/TabBar/TabBarCollectionViewCell.swift
  Kurly/Kurly/Presentation/Common/TabBar/TabBarRect.swift
  Kurly/Kurly/Presentation/Common/TabBar/TabBarView.swift
  Kurly/Kurly/Presentation/Common/UIComponents/BottomCTAButton.swift
  Kurly/Kurly/Presentation/Common/UIComponents/CustomNavigationBar.swift
  Kurly/Kurly/Presentation/Detail/ViewController/DetailViewController.swift
Labels: Feature, 민주

#11 [Feature] #9 - 상품 담기 뷰 UI와 로직을 구현했습니다.
  Kurly/Kurly/Global/Extension/String+.swift
  Kurly/Kurly/Global/Literals/ImageLiterals.swift
  Kurly/Kurly/Presentation/AddCart/Components/Stepper.swift
  Kurly/Kurly/Presentation/AddCart/Models/Product.swift
  Kurly/Kurly/Presentation/AddCart/ViewControllers/AddCartViewController.swift
  Kurly/Kurly/Presentation/AddCart/ViewControllers/TestViewController.swift
  Kurly/Kurly/Presentation/AddCart/Views/AddCartView.swift
  Kurly/Kurly/Presentation/Common/UIComponents/BottomCTAButton.swift
Labels: Feature, 민주, UI

#17 [Feature] #16 - 장바구니 뷰 UI (상단, 하단) 를 구현했습니다.
  Kurly/Kurly.xcodeproj/project.pbxproj
  Kurly/Kurly/Presentation/Cart/ViewControllers/CartViewController.swift
  Kurly/Kurly/Presentation/Cart/Views/CartView.swift
  Kurly/Kurly/Presentation/Common/UIComponents/CustomNavigationBar.swift
Labels: Feature, Fix, 준혁, UI

#23 [Feature] #15 - 상품 상세보기 뷰 전체 컬렉션뷰/첫 번째 섹션 구현하였습니다.
  Kurly/Kurly.xcodeproj/project.pbxproj
  Kurly/Kurly/Global/Literals/ColorLiterals.swift
  Kurly/Kurly/Global/Literals/ImageLiterals.swift
  Kurly/Kurly/Presentation/Common/TabBar/TabBarView.swift
  Kurly/Kurly/Presentation/Detail/Models/DetailProduct.swift
  Kurly/Kurly/Presentation/Detail/ViewControllers/DetailViewController.swift
  Kurly/Kurly/Presentation/Detail/Views/DetailView.swift
  Kurly/Kurly/Presentation/Detail/Views/FirstSectionCollectionViewCell.swift
Labels: Feature, 보연, UI

#26 [Fix] #25 - 이미지 이름 수정, makeCornerRound로 변경했습니다.
  Kurly/Kurly/Presentation/FavoriteFood/View/NotifyAddToastView.swift
  Kurly/Kurly/Presentation/FavoriteFood/View/NotifyRemoveToastView.swift
  Kurly/Kurly/Presentation/RelatedFoodModal/Cells/RecommendCollectionViewCell.swift
  Kurly/Kurly/Presentation/RelatedFoodModal/Views/RecommendHeaderView.swift
  Kurly/Kurly/Presentation/RelatedFoodModal/Views/RelatedFoodModalView.swift
Labels: Fix, 민수, UI

#29 [Feature] #28 - 연관 상품, 추천 상품 모달 뷰의 모델과 데이터를 연결했습니다.
  Kurly/Kurly.xcodeproj/project.pbxproj
  Kurly/Kurly/Presentation/RelatedFoodModal/Cells/RecommendCollectionViewCell.swift
  Kurly/Kurly/Presentation/RelatedFoodModal/Models/RecommendModel.swift
  Kurly/Kurly/Presentation/RelatedFoodModal/ViewControllers/RelatedFoodModalViewController.swift
Labels: Feature, 민수

#30 [Feature] 상세보기 뷰 두 번째 섹션 구현하였습니다.
  Kurly/Kurly.xcodeproj/project.pbxproj
  Kurly/Kurly/Presentation/Detail/Views/DetailView.swift
  Kurly/Kurly/Presentation/Detail/Views/FirstSectionCollectionViewCell.swift
  Kurly/Kurly/Presentation/Detail/Views/SecondSectionCollectionViewCell.swift
Labels: Feature, 보연, UI

#32 [Feature] #12 - 장바구니 담기 버튼을 누르면 생성되는 뷰 UI를 구현했습니다.
  Kurly/Kurly.xcodeproj/project.pbxproj
  Kurly/Kurly/Global/Extension/Int+.swift
  Kurly/Kurly/Global/Extension/UILabel+.swift
  Kurly/Kurly/Presentation/AddCart/ViewControllers/AddCartViewController.swift
  Kurly/Kurly/Presentation/AddCart/ViewControllers/TestViewController.swift
  Kurly/Kurly/Presentation/AddCart/Views/AddCartView.swift
  Kurly/Kurly/Presentation/AfterAddCart/ViewControllers/AfterAddCartViewController.swift
  Kurly/Kurly/Presentation/AfterAddCart/Views/AfterAddCartView.swift
Labels: Feature, 민주, UI

#33 [Feature] #31 - 상세보기 뷰 세 번째 섹션 구현하였습니다.
  Kurly/Kurly.xcodeproj/project.pbxproj
  Kurly/Kurly/Presentation/Detail/Views/DetailView.swift
  Kurly/Kurly/Presentation/Detail/Views/ThridSectionHorizontalCollectionViewCell.swift
Labels: Feature, 보연, UI

#36 [Feature] #27 - 장바구니 뷰의 첫번째 섹션을 구현했습니다.
  Kurly/Kurly.xcodeproj/project.pbxproj
  Kurly/Kurly/Presentation/Cart/Cells/CartItemCollectionViewCell.swift
  Kurly/Kurly/Presentation/Cart/ViewControllers/CartViewController.swift
  Kurly/Kurly/Presentation/Cart/Views/CartHeaderView.swift
  Kurly/Kurly/Presentation/Cart/Views/CartItemHeaderCollectionReusableView.swift
  Kurly/Kurly/Presentation/Cart/Views/CartView.swift
Labels: Feature, Fix, 준혁, UI

#38 [Feature] #35 - 상세보기 뷰 네 번째 섹션 구현하였습니다.
  Kurly/Kurly.xcodeproj/project.pbxproj
  Kurly/Kurly/Presentation/Detail/ViewControllers/DetailViewController.swift
  Kurly/Kurly/Presentation/Detail/Views/DetailView.swift
  Kurly/Kurly/Presentation/Detail/Views/FirstSectionCollectionViewCell.swift
  Kurly/Kurly/Presentation/Detail/Views/FourthSectionCollectionViewCell.swift
  Kurly/Kurly/Presentation/Detail/Views/SecondSectionCollectionViewCell.swift
  Kurly/Kurly/Presentation/Detail/Views/ThridSectionHorizontalCollectionViewCell.swift
Labels: Feature, 보연, UI

#40 [Feature]#39 - 상세보기 뷰 다섯 번째 섹션 구현하였습니다.
  Kurly/Kurly.xcodeproj/project.pbxproj
  Kurly/Kurly/Presentation/Detail/ViewControllers/DetailViewController.swift
  Kurly/Kurly/Presentation/Detail/Views/FifthSectionCollectionViewCell.swift
Labels: Feature, 보연, UI

#44 [Feature] #41 - 상세보기 뷰 여섯 번째 섹션 구현하였습니다.
  Kurly/Kurly.xcodeproj/project.pbxproj
  Kurly/Kurly/Presentation/Detail/ViewControllers/DetailViewController.swift
  Kurly/Kurly/Presentation/Detail/Views/SixthSectionCollectionViewCell.swift
Labels: Feature, 보연, UI

#42 [Feature] #34 - 장바구니에 담으면 나타나는 뷰 UI를 구현했습니다.
  Kurly/Kurly.xcodeproj/project.pbxproj
  Kurly/Kurly/Presentation/AfterAddCart/Cells/RelatedCollectionViewCell.swift
  Kurly/Kurly/Presentation/AfterAddCart/Model/RelatedModel.swift
  Kurly/Kurly/Presentation/AfterAddCart/ViewControllers/AfterAddCartViewController.swift
  Kurly/Kurly/Presentation/AfterAddCart/Views/AfterAddCartView.swift
Labels: Feature, 민주, UI

#46 [Fix] #45 - 전체 컬렉션 뷰 레이아웃 수정
  Kurly/Kurly/Presentation/Detail/ViewControllers/DetailViewController.swift
  Kurly/Kurly/Presentation/Detail/Views/DetailView.swift
Labels: Fix, 보연

#53 [Feature] #52 주문 완료 뷰를 상, 하단을 구현했습니다.
  Kurly/Kurly.xcodeproj/project.pbxproj
  Kurly/Kurly/Presentation/CompletedOrder /ViewController/CompletedOrderViewController.swift
  Kurly/Kurly/Presentation/CompletedOrder /Views/CompletedOrderView.swift
Labels: Feature, 준혁, UI

#50 [Feature] #49 - 플로팅 버튼 구현하였습니다.
  Kurly/Kurly.xcodeproj/project.pbxproj
  Kurly/Kurly/Presentation/Detail/Components/FloatingButton.swift
  Kurly/Kurly/Presentation/Detail/ViewControllers/DetailViewController.swift
Labels: Feature, 보연, UI

#51 [Feature] #37 장바구니 뷰의 두번째 섹션을 구현했습니다.
  Kurly/Kurly.xcodeproj/project.pbxproj
  Kurly/Kurly/Presentation/Cart/Cells/OrderPriceCollectionViewCell.swift
  Kurly/Kurly/Presentation/Cart/ViewControllers/CartViewController.swift
  Kurly/Kurly/Presentation/Cart/Views/CartHeaderView.swift
  Kurly/Kurly/Presentation/Cart/Views/CartItemFooterCollectionReusableView.swift
  Kurly/Kurly/Presentation/Cart/Views/CartItemHeaderCollectionReusableView.swift
  Kurly/Kurly/Presentation/Cart/Views/CartView.swift
  Kurly/Kurly/Presentation/Cart/Views/SavePointView.swift
Labels: Feature, Fix, 준혁, UI

#56 [Add] #55 - CTA Button 경우의 수 추가
  Kurly/Kurly/Presentation/Common/UIComponents/BottomCTAButton.swift
Labels: Feature, 보연

#58 [Feature] #34 - 물품 개수 변경에 가격도 함께 바뀌는 로직을 구현했습니다.
  Kurly/Kurly.xcodeproj/project.pbxproj
  Kurly/Kurly/Presentation/AddCart/ViewControllers/AddCartViewController.swift
  Kurly/Kurly/Presentation/AddCart/ViewControllers/CustomAlertViewController.swift
  Kurly/Kurly/Presentation/AddCart/Views/AddCartView.swift
  Kurly/Kurly/Presentation/AddCart/Views/AlertBuilder.swift
Labels: Feature, 민주

#59 [Feature] #54 주문 완료 뷰 ( 중앙 )를 구현했습니다.
  Kurly/Kurly.xcodeproj/project.pbxproj
  Kurly/Kurly/Presentation/CompletedOrder /ViewController/CompletedOrderViewController.swift
  Kurly/Kurly/Presentation/CompletedOrder /Views/BenefitsInfoView.swift
  Kurly/Kurly/Presentation/CompletedOrder /Views/CompletedOrderView.swift
Labels: Feature, 준혁, UI

#60 [Feature] #57 - 찜하기 버튼 선택 시 토스트 메세지 뷰 띄우기 구현하였습니다.
  Kurly/Kurly.xcodeproj/project.pbxproj
  Kurly/Kurly/Presentation/Detail/ViewControllers/DetailViewController.swift
  Kurly/Kurly/Presentation/FavoriteFood/ViewControllers/sampleViewController.swift
Labels: Feature, 보연

#65 [Feature] #63 - 구매하기 버튼 선택 시 띄우는 모달 뷰를 연결합니다.
  Kurly/Kurly.xcodeproj/project.pbxproj
  Kurly/Kurly/Presentation/AddCart/ViewControllers/AddCartViewController.swift
  Kurly/Kurly/Presentation/AddCart/ViewControllers/TestViewController.swift
  Kurly/Kurly/Presentation/Detail/ViewControllers/DetailViewController.swift
Labels: Feature, Fix, 보연

#67 [Feature] 장바구니에 상품이 없는 View 를 구현 및 분기처리 하였습니다.
  Kurly/Kurly.xcodeproj/project.pbxproj
  Kurly/Kurly/Global/Literals/ImageLiterals.swift
  Kurly/Kurly/Global/Resources/Assets/Assets.xcassets/ic_Error_defult.imageset/Contents.json
  Kurly/Kurly/Global/Resources/Assets/Assets.xcassets/ic_Error_defult.imageset/ic_Error_defult.svg
  Kurly/Kurly/Presentation/Cart/ViewControllers/CartViewController.swift
  Kurly/Kurly/Presentation/Cart/Views/CartHeaderView.swift
  Kurly/Kurly/Presentation/Cart/Views/CartView.swift
  Kurly/Kurly/Presentation/Cart/Views/EmptyItemView.swift
Labels: Feature, Fix, 준혁, UI

#70 [Fix] #69 - ToastView 레이아웃 수정
  Kurly/Kurly/Presentation/FavoriteFood/View/NotifyAddToastView.swift
  Kurly/Kurly/Presentation/FavoriteFood/View/NotifyRemoveToastView.swift
Labels: Fix, 민수, UI

#72 [Feature] #64 - Custom CollectionView를 구현했습니다.
  Kurly/Kurly.xcodeproj/project.pbxproj
  Kurly/Kurly/Presentation/AfterAddCart/Model/RelatedModel.swift
  Kurly/Kurly/Presentation/AfterAddCart/ViewControllers/AfterAddCartViewController.swift
  Kurly/Kurly/Presentation/AfterAddCart/Views/AfterAddCartView.swift
  Kurly/Kurly/Presentation/Common/UIComponents/CustomCollectionView/CustomCollectionView.swift
  Kurly/Kurly/Presentation/Common/UIComponents/CustomCollectionView/CustomCollectionViewCell.swift
  Kurly/Kurly/Presentation/Common/UIComponents/CustomCollectionView/CustomFooterView.swift
  Kurly/Kurly/Presentation/Common/UIComponents/CustomCollectionView/CustomHeaderView.swift
Labels: Feature, 민주, UI

#76 [Setting] #75 - CollectionView Protocol 파일 추가
  Kurly/Kurly.xcodeproj/project.pbxproj
  Kurly/Kurly/Global/Protocols/CollectionViewCellRegisterDequeueProtocol.swift
  Kurly/Kurly/Global/Protocols/Protocols.swift
Labels: 보연, Setting

#80 [Fix] #77 - UICollectionView register 리팩토링합니다.
  Kurly/Kurly/Presentation/Cart/Cells/CartItemCollectionViewCell.swift
  Kurly/Kurly/Presentation/Cart/Cells/OrderPriceCollectionViewCell.swift
  Kurly/Kurly/Presentation/Cart/ViewControllers/CartViewController.swift
  Kurly/Kurly/Presentation/Detail/Cells/FifthSectionCollectionViewCell.swift
  Kurly/Kurly/Presentation/Detail/Cells/FirstSectionCollectionViewCell.swift
  Kurly/Kurly/Presentation/Detail/Cells/FourthSectionCollectionViewCell.swift
  Kurly/Kurly/Presentation/Detail/Cells/SecondSectionCollectionViewCell.swift
  Kurly/Kurly/Presentation/Detail/Cells/SixthSectionCollectionViewCell.swift
  Kurly/Kurly/Presentation/Detail/Cells/ThridSectionHorizontalCollectionViewCell.swift
  Kurly/Kurly/Presentation/Detail/ViewControllers/DetailViewController.swift
  Kurly/Kurly/Presentation/RelatedFoodModal/Cells/RecommendCollectionViewCell.swift
  Kurly/Kurly/Presentation/RelatedFoodModal/ViewControllers/RelatedFoodModalViewController.swift
Labels: Fix, 보연

#78 [Feature] #68 - 상품 결제 금액에 관한 로직을 구현했습니다.
  Kurly/Kurly.xcodeproj/project.pbxproj
  Kurly/Kurly/Presentation/Cart/Cells/CartItemCollectionViewCell.swift
  Kurly/Kurly/Presentation/Cart/Cells/OrderPriceCollectionViewCell.swift
  Kurly/Kurly/Presentation/Cart/Model/CartModel.swift
  Kurly/Kurly/Presentation/Cart/Model/OrderModel.swift
  Kurly/Kurly/Presentation/Cart/ViewControllers/CartViewController.swift
  Kurly/Kurly/Presentation/Cart/Views/CartHeaderView.swift
  Kurly/Kurly/Presentation/Cart/Views/CartView.swift
Labels: Feature, Fix, 준혁, UI

#83 [Setting] #81 - CollectionView Header, Footer Protocol 파일 추가
  Kurly/Kurly.xcodeproj/project.pbxproj
  Kurly/Kurly/Global/Protocols/CollectionHeaderViewRegisterDequeueProtocol.swift
Labels: 보연, Setting

#85 [Fix] #84 - UICollectionView Header, Footer register 리팩토링했습니다.
  Kurly/Kurly/Presentation/Cart/ViewControllers/CartViewController.swift
  Kurly/Kurly/Presentation/Cart/Views/CartItemFooterCollectionReusableView.swift
  Kurly/Kurly/Presentation/Cart/Views/CartItemHeaderCollectionReusableView.swift
  Kurly/Kurly/Presentation/Detail/ViewControllers/DetailViewController.swift
  Kurly/Kurly/Presentation/RelatedFoodModal/ViewControllers/RelatedFoodModalViewController.swift
  Kurly/Kurly/Presentation/RelatedFoodModal/Views/RecommendFooterView.swift
  Kurly/Kurly/Presentation/RelatedFoodModal/Views/RecommendHeaderView.swift
Labels: Fix, 보연

#89 [Fix] #79 - CustomCollectionView로 수정했습니다.
  Kurly/Kurly/Presentation/Detail/Cells/ThridSectionHorizontalCollectionViewCell.swift
  Kurly/Kurly/Presentation/RelatedFoodModal/ViewControllers/RelatedFoodModalViewController.swift
  Kurly/Kurly/Presentation/RelatedFoodModal/Views/RelatedFoodModalView.swift
Labels: Fix, 민수

#92 [Feature] #88 - 장바구니 무료 배송 API를 연결하였습니다.
  Kurly/Kurly.xcodeproj/project.pbxproj
  Kurly/Kurly/Network/Base/NetworkRequest.swift
  Kurly/Kurly/Network/DTO/ProductResponse.swift
  Kurly/Kurly/Network/Service/CartService.swift
  Kurly/Kurly/Network/Service/ProductService.swift
  Kurly/Kurly/Presentation/AfterAddCart/ViewControllers/AfterAddCartViewController.swift
  Kurly/Kurly/Presentation/AfterAddCart/Views/AfterAddCartView.swift
Labels: Feature, Fix, 민주

#90 [Feature] #82 - 장바구니 뷰 Sticky Header 구현했습니다.
  Kurly/Kurly.xcodeproj/project.pbxproj
  Kurly/Kurly/Presentation/Cart/Cells/CartItemCollectionViewCell.swift
  Kurly/Kurly/Presentation/Cart/ViewControllers/CartViewController.swift
  Kurly/Kurly/Presentation/Cart/Views/AllSelectedItemView.swift
  Kurly/Kurly/Presentation/Cart/Views/CartAddressView.swift
  Kurly/Kurly/Presentation/Cart/Views/CartHeaderView.swift
  Kurly/Kurly/Presentation/Cart/Views/CartView.swift
Labels: Feature, Fix, 준혁, UI

#94 [Feature] #93 - 장바구니 담기 API를 연결하였습니다.
  Kurly/Kurly.xcodeproj/project.pbxproj
  Kurly/Kurly/Network/Base/NetworkRequest.swift
  Kurly/Kurly/Network/DTO/CartRequest.swift
  Kurly/Kurly/Network/Service/CartService.swift
  Kurly/Kurly/Network/Service/ProductService.swift
  Kurly/Kurly/Presentation/AddCart/ViewControllers/AddCartViewController.swift
  Kurly/Kurly/Presentation/AfterAddCart/ViewControllers/AfterAddCartViewController.swift
  Kurly/Kurly/Presentation/AfterAddCart/Views/AfterAddCartView.swift
Labels: Feature, 민주

#102 [Feature] #98 함께 구매하면 좋은 상품 API를 연결합니다.
  Kurly/Kurly.xcodeproj/project.pbxproj
  Kurly/Kurly/Network/DTO/RecommendResponse.swift
  Kurly/Kurly/Network/Service/RecommendService.swift
  Kurly/Kurly/Network/Service/RelatedFoodService.swift
  Kurly/Kurly/Presentation/RelatedFoodModal/ViewControllers/RelatedFoodModalViewController.swift
Labels: Feature, 민수
